[package]
name = "scpi_example"
version = "0.1.0"
authors = ["Atmelfan <gustavp@gpa-robotics.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scpi = {path = "../scpi"}