# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "rust:cargo"
    # Look for a workspace
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "live"
