//! # 16 PROGram Subsystem
//! The purpose of the PROGram subsystem is to provide the administrative features needed to
//! generate and control one or more user-programmed tasks resident in an instrument. Two
//! distinct methods of accessing a particular program are provided in the PROGram
//! subysystem. One method employs EXPLicit reference for each command, allowing access to
//! all programs, but requires the program name to be always specified. The other method
//! allows a single program to be SELected at a time, and the related commands access only the
//! currently selected program. If the EXPLicit method is implemented, then the SELected
//! method shall also be implemented.
//!
//! A *RST received from a remote controller, via the device interface, shall cause all programs
//! to be stopped.
//!
//! A *RST generated by a program running in the device shall cause the same effect as a *RST
//! received from a remote controller, with the exception that the program that generated the
//! *RST shall not be forced to stop. It is necessary for a *RST to behave in this manner so that
//! a program, when run on either a remote controller or the device, shall have the same effect.