//! # 24 TRIGger Subsystem
//! The trigger subsystem is used to synchronize device action(s) with events. A device action
//! might be the acquisition of a measurement or the application of a stimulus. The trigger
//! subsystem consists of the expanded capability model which is capable of describing very
//! complex device trigger systems. It also makes provision, through the ARM-TRIGger model,
//! for simple descriptions of less complicated trigger systems. These two models are consistent
//! and compatible with each other. The ARM-TRIGger model represents a subset of the
//! capability available in the expanded capability model.
//!
//! The figures in this section that represent the trigger model adhere to the following
//! nomenclature. A box identifies a state of a transition diagram and is referred to as a layer. A
//! sequence is a set of vertically connected layers. A solid line defines flow of control between
//! states. A dashed line defines how an event is propagated to other parts of the trigger model
//! and the instrument. Events generated by control flowing from one part of the trigger model
//! to another part are called “sequence events.”